// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYaW_UYmjwjp3mlGwEdnGpwWv-YqnSjlc',
    appId: '1:926896961952:web:23f42ef60520a9568fccc5',
    messagingSenderId: '926896961952',
    projectId: 'testiosproject-7c1f5',
    authDomain: 'testiosproject-7c1f5.firebaseapp.com',
    storageBucket: 'testiosproject-7c1f5.firebasestorage.app',
    measurementId: 'G-RXYZN70ERK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQCLF2DwcVqmGSJYDe-Bwk9PoHhgbzIw',
    appId: '1:926896961952:android:f83a0c6b13f353428fccc5',
    messagingSenderId: '926896961952',
    projectId: 'testiosproject-7c1f5',
    storageBucket: 'testiosproject-7c1f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsBjqVuir1xUTIJ8UurUV-iM-OQ96ElQM',
    appId: '1:926896961952:ios:081302e899a0c90e8fccc5',
    messagingSenderId: '926896961952',
    projectId: 'testiosproject-7c1f5',
    storageBucket: 'testiosproject-7c1f5.firebasestorage.app',
    iosBundleId: 'com.example.schoolmanagementsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsBjqVuir1xUTIJ8UurUV-iM-OQ96ElQM',
    appId: '1:926896961952:ios:081302e899a0c90e8fccc5',
    messagingSenderId: '926896961952',
    projectId: 'testiosproject-7c1f5',
    storageBucket: 'testiosproject-7c1f5.firebasestorage.app',
    iosBundleId: 'com.example.schoolmanagementsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYaW_UYmjwjp3mlGwEdnGpwWv-YqnSjlc',
    appId: '1:926896961952:web:cfca006260c2663b8fccc5',
    messagingSenderId: '926896961952',
    projectId: 'testiosproject-7c1f5',
    authDomain: 'testiosproject-7c1f5.firebaseapp.com',
    storageBucket: 'testiosproject-7c1f5.firebasestorage.app',
    measurementId: 'G-6SRSN8XDTV',
  );
}
